name: CI-with-docker

on: 
  workflow_dispatch:

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: checkout td_env
      uses: actions/checkout@v3
      with:
         fetch-depth: 1
         ref: ''
    - name: Load and run image
      run: |
        docker pull lsstdesc/td-env:dev
        cd $GITHUB_WORKSPACE
        docker run -u lsst -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE -w /opt/lsst/software/stack lsstdesc/td-env:dev /bin/bash /docker/td-env-test.sh
         
